GPCRtrack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),

]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    #path('login/', views.login_view, name='login'),
    path('entry/', views.entry, name='entry'),
    path('entry_success/', views.entry_success, name='entry_success'),
    path('search/', views.search, name='search'),
    path('apply/<str:construct_number>/', views.apply, name='apply'),
    path('apply_success/', views.apply_success, name='apply_success'),
    path('edit/<str:construct_number>/', views.edit, name='edit'),
    path('delete/<str:construct_number>/', views.delete, name='delete'),
    path('application/', views.application, name='application'),
    path('export/', views.export, name='export'),
    path('statistics/', views.statistics, name='statistics'),
]

app/templates/app/application.html
{% extends 'app/home.html' %}

{% block content %}
    <h2>Create A Expression Request</h2>
    <form method="post">
        {% csrf_token %}
        <p><label for="construct_number">Construct Number:</label></p>
        <p><input type="text" id="construct_number" name="construct_number" value="{{ construct_number }}" readonly><br></p>
        <p><label for="P">P(enter numbers only, 0 or 1):</label></p>
        <p><input type="number" id="P" name="P" required><br></p>
        <p><label for="biomass ">Biomass:</label></p>
        <p><input type="number" id="biomass" name="biomass" required><br></p>
        <p><label for="expression_system">Expression System:</label></p>
        <p><input type="text" id="expression_system" name="expression_system" required><br></p>
        <p><label for="application_user">Created By:</label></p>
        <p><input type="text" id="application_user" name="application_user"><br></p>
        <p><label for="comment">Comment:</label></p>
        <p><textarea id="comment" name="comment"></textarea><br></p>
        <p><input type="submit" value="Submit"></p>
    </form>

    <a href="{% url 'app:home' %}">Back to home</a>
    <h2>Application History</h2>
    {% if application_items %}
        <ol>
            {% for application_item in application_items %}
                <li>
                    <p><strong>construct_number:</strong> {{ application_item.construct_number }}</p>
                    <p><strong>P:</strong> {{ application_item.P }}</p>
                    <p><strong>Biomass:</strong> {{ application_item.biomass }}</p>
                    <p><strong>Expression System:</strong> {{ application_item.expression_system }}</p>
                    <p><strong>Application Time:</strong> {{ application_item.application_time }}</p>
                    <p><strong>Application user:</strong> {{ application_item.application_user }}</p>
                    <p><strong>Comment:</strong> {{ application_item.comment }}</p>
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <p>No application records found.</p>
    {% endif %}
    <a href="{% url 'app:home' %}">Back to home</a>
{% endblock %}

app/templates/app/apply_success.html
{% extends 'app/home.html' %}
{% block content %}
    <h2>Created Expression Request Successfully!</h2>
    <ul>
    <li><a href="{% url 'app:home' %}">Back to home</a></li>
    <li><a href="{% url 'app:entry' %}">Create Construct</a></li>
    <li><a href="{% url 'app:search' %}">Search and Create Another Request </a></li>
    </ul>
{% endblock %}

app/templates/app/base.html
<!DOCTYPE html>
<html>
<head>
    <title>My Website</title>
</head>
<body>
    <div class="container">
        <header>
            <h1>My Website</h1>
        </header>
        <nav>
            <ul>
                <li><a href="{% url 'app:home' %}">Home</a></li>
                <li><a href="{% url 'app:entry' %}">Entry</a></li>
                <li><a href="{% url 'app:search' %}">Search</a></li>
            </ul>
        </nav>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </div>
</body>
</html>

app/templates/app/delete.html
{% extends 'app/home.html' %}

{% block content %}
    <h2>Delete Construct Item</h2>
    <p>Are you sure you want to delete the construct item with the construct number: <strong>{{ construct_item.construct_number }}</strong>?</p>
    <p>All information of <strong>{{ construct_item.construct_number }}</strong> and related application records WILL BE DELETED IRRETRIEVABLY!!!</p>
    <form method="post">
        {% csrf_token %}
        <p><input type="submit" value="Delete"></p>
    </form>
    <p><a href="{% url 'app:home' %}">Back to home</a></p>
{% endblock %}

app/templates/app/edit.html
{% extends 'app/home.html' %}

{% block content %}
    <h2>Edit Construct Item</h2>
    <form method="post">
        {% csrf_token %}
        <p><label for="construct_number">Construct Number:</label></p>
        <p><input type="text" id="construct_number" name="construct_number" value="{{ construct_item.construct_number }}" readonly><br></p>
        <p><label for="receptor">Receptor:</label></p>
        <p><input type="text" id="receptor" name="receptor" value="{{ construct_item.receptor }}" required><br></p>
        <p><label for="DNA_sequence">DNA Sequence:</label></p>
        <p><textarea id="DNA_sequence" name="DNA_sequence" required>{{ construct_item.DNA_sequence }}</textarea><br></p>
        <p><label for="description">Description:</label></p>
        <p><textarea id="description" name="description" required>{{ construct_item.description }}</textarea><br></p>
        <p><label for="comment">Comment:</label></p>
        <p><textarea id="comment" name="comment">{{ construct_item.comment }}</textarea><br></p>
        <p><label for="user">User:</label></p>
        <p><textarea id="user" name="user">{{ construct_item.user }}</textarea><br></p>
        </p><input type="submit" value="Save Changes"></p>
    </form>
    <a href="{% url 'app:home' %}">Back to home</a>
{% endblock %}

app/templates/app/entry.html
{% extends 'app/home.html' %}

{% block content %}
    <h2>Create A New Construct</h2>
    <form method="post">
        {% csrf_token %}
        <p><label for="construct_number">Construct Number:</label></p>
        <p><input type="text" id="construct_number" name="construct_number" value="{{ construct_number }}" readonly><br></p>
        <p><label for="receptor">Receptor:</label></p>
        <p><input type="text" id="receptor" name="receptor" required><br></p>
        <p><label for="DNA_sequence">DNA Sequence:</label></p>
        <p><textarea id="DNA_sequence" name="DNA_sequence" required></textarea><br></p>
        <p><label for="description">Description(eg. promoter/tag/fusion/truncation/junction):</label></p>
        <p><textarea id="description" name="description" required></textarea><br></p>
        <p><label for="comment">Comment:</label></p>
        <p><textarea id="comment" name="comment"></textarea><br></p>
        <p><label for="user">User:</label></p>
        <p><textarea id="user" name="user"></textarea><br></p>
        <p><input type="submit" value="Submit"></p>
    </form>
    <a href="{% url 'app:home' %}">Back to home</a>
{% endblock %}

app/templates/app/entry_success.html
{% extends 'app/home.html' %}
{% block content %}
    <h2>Created Successfully!</h2>
    <ul>
    <li><a href="{% url 'app:home' %}">Back to home</a></li>
    <li><a href="{% url 'app:entry' %}">Create Another Construct</a></li>
    <li><a href="{% url 'app:search' %}">Search</a></li>
    </ul>
{% endblock %}

app/templates/app/export.html
{% extends 'app/home.html' %}
{% load static %}

{% block content %}
    <h2>Export Application Records</h2>
    <p>Search applications.</p>
    <p>Examples:</p>
    <p>Search data between 2023-06-04 00:00 and 2023-06-04 23:59</p>
    <p>input:Start Date=2023-06-04, End Date=2023-06-04</p>

    <form method="post">
        {% csrf_token %}
        <p><label for="start_date">Start Date:</label></p>
        <p><input type="date" id="start_date" name="start_date" required><br></p>
        <p><label for="end_date">End Date:</label></p>
        <p><input type="date" id="end_date" name="end_date" required><br></p>
        <p><input type="submit" value="Search And Export"></p>
    </form>
    {% if exported %}
        <p>Exported successfully! <a href="{% static  csv_file_url  %}" download="{{ basename }}"><button>Download CSV file</button></a></p>
    {% endif %}
    {% if no_filtered_files %}
        <p>No applications found within the assigned date.</p>
        <p>Please try again.</p>
    {% endif %}
    <p><a href="{% url 'app:home' %}">Back to home</a></p>
{% endblock %}

app/templates/app/home.html
{% block content %}
    <h2>Welcome to GPCRtrack!</h2>
    <p>Choose an option:</p>
    <ul>
        <li><a href="{% url 'app:entry' %}">Create A New Construct</a></li>
        <li><a href="{% url 'app:search' %}">Search Construct for Expression Request</a></li>
        <li><a href="{% url 'app:export' %}">Export Expression Requests</a></li>
        <li><a href="{% url 'app:statistics' %}">Statistics</a></li>

    </ul>
{% endblock %}

app/templates/app/login.html
{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br>
        <input type="submit" value="Login">
    </form>
{% endblock %}

app/templates/app/search.html
{% extends 'app/home.html' %}

{% block content %}
    <h2>Search</h2>
    <form method="post">
        {% csrf_token %}
        <label for="construct_number">Construct Number:</label>
        <input type="text" id="construct_number" name="construct_number" required><br>
        <p><input type="submit" value="Search"></p>
    <a href="{% url 'app:home' %}">Back to home</a>
    </form>
    {% if construct_item %}
        <h3>Construct Information:</h3>
        <p><strong>Construct Number:</strong> {{ construct_item.construct_number }}</p>
        <p><strong>Receptor:</strong> {{ construct_item.receptor }}</p>
        <p><strong>DNA Sequence:</strong> {{ construct_item.DNA_sequence }}</p>
        <p><strong>Description:</strong> {{ construct_item.description }}</p>
        <p><strong>Comment:</strong> {{ construct_item.comment }}</p>
        <p><strong>Created By:</strong> {{ construct_item.user }}</p>
        <a href="{% url 'app:home' %}">Back to home</a>
        <h3>More Operations:</h3>
        <ul>
            <li><a href="{% url 'app:apply' construct_item.construct_number %}">Expression Request</a></li>
            <li><a href="{% url 'app:edit' construct_item.construct_number %}">Edit Construct Info</a></li>
            <li><a href="{% url 'app:delete' construct_item.construct_number %}">Delete Construct Info</a></li>
        </ul>
        <h3>Application History:</h3>
        {% if application_items %}
            <ol>
                {% for application_item in application_items %}
                    <li>
                        <p><strong>Construct Number:</strong> {{ application_item.construct_number }}</p>
                        <p><strong>P:</strong> {{ application_item.P }}</p>
                        <p><strong>Biomass:</strong> {{ application_item.biomass }}</p>
                        <p><strong>Expression System:</strong> {{ application_item.expression_system }}</p>
                        <p><strong>Application Time:</strong> {{ application_item.application_time }}</p>
                        <p><strong>Application user:</strong> {{ application_item.application_user }}</p>
                        <p><strong>Comment:</strong> {{ application_item.comment }}</p>
                    </li>
                {% endfor %}
            </ol>
        {% else %}
            <p>No application records found.</p>
        {% endif %}

    {% else %}
        <p>No construct item found. Please try again.</p>
    {% endif %}
    <a href="{% url 'app:home' %}">Back to home</a>
{% endblock %}

app/templates/app/statistics.html
{% extends 'app/home.html' %}
{% load static %}

{% block content %}
<h2>Global Statistics</h2>
    <p>Number of constructs: {{ len_constructItems }}</p>
    <p>Number of expression requests: {{ len_applicationItems }}</p>
    <p>Number of receptors: {{ len_receptors }}</p>
    <p>Number of users: {{ user_count }}</p>

    {% if export_all_construct %}
        <p> <a href="{% static  all_construct_csv_file_url  %}" download="{{ all_construct_basename }}"><button>Download All Construct CSV file</button></a></p>
    {% endif %}
    {% if export_all_application %}
        <p> <a href="{% static  all_application_csv_file_url  %}" download="{{ all_application_basename }}"><button>Download All Application CSV file</button></a></p>
    {% endif %}

    <p><a href="{% url 'app:home' %}">Back to home</a></p>

{% endblock %}